[build-system]
build-backend = "cmeel"
requires = [
  "cmeel[build]",
  "pin[build] >=  3",
  "rhoban-cmeel-jsoncpp"
]

[project]
authors = [{ email = "team@rhoban.com", name = "Rhoban team" }]
classifiers = []
dependencies = [
  "eiquadprog >= 1.2.6, < 2",
  "pin >= 3",
  "rhoban-cmeel-jsoncpp",
  "meshcat",
  "ischedule"
]
description = "Build wheel test"
license = "MIT"
name = "placo"
requires-python = ">= 3.9"
version = "0.0.1"

[tool.isort]
profile = "black"

[tool.ruff]
target-version = "py39"

[tool.tomlsort]
all = true

[tool.cmeel]
run-tests = false
