name: Build

on: [push, pull_request]

env:
  CIBW_BUILD: "cp310-manylinux_x86_64"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Set PATH
        run: echo "export PATH=\$PATH:/usr/local/bin" >> $GITHUB_ENV

      - uses: ssciwr/doxygen-install@v1
        with:
          version: "1.13.2"

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip 

      - uses: actions/checkout@v4
      
      - name: execute py script # run file
        run: |
          python test_doxygen.py


      # # Used to host cibuildwheel
      # - uses: actions/setup-python@v5

      # - name: Install cibuildwheel
      #   run: python -m pip install cibuildwheel==3.0.0b1

      # - name: Build wheels
      #   run: python -m cibuildwheel --output-dir wheelhouse
      #   # to supply options, put them in 'env', like:
      #   # env:
      #   #   CIBW_SOME_OPTION: value
      #   #   ...

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
      #     path: ./wheelhouse/*.whl